// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vchajpctzwzgihrqdoxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaGFqcGN0end6Z2locnFkb3h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjUzODQsImV4cCI6MjA3NDU0MTM4NH0.LbpGFdBdoVor90KfMRDO0J0w935HDMAMqBSFZVs4XUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});